# Generated by Django 3.0.6 on 2020-06-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_auto_20200615_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('cellphone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='study',
            old_name='category',
            new_name='category_id',
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('user_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('study_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.Study')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.Study')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPicture',
            fields=[
                ('activity_picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.Study')),
            ],
        ),
    ]
