# Generated by Django 3.0.6 on 2020-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_auto_20200617_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymember',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
